# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f79c604c31d859f019da27d61824d189f0756077bea33c508e23c85b6b27dcea8d062560a6deb46f8ae90111977b129182afb9a64f7276c9f2fd898361ade8c

test:
  secret_key_base: d9b1f130e50ff74b8a68dcc60cbc9f5f41047f5bd076cbdc27bc2c39d221bc7c12b861fbee4424aff48db2ce64b1c8f9ee4ac1df9135639a1939714e2d51cf1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
